# Generated by Django 3.2 on 2022-09-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscription',
            field=models.ManyToManyField(related_name='followed_by', through='account.Subscription', to='account.UserProfile'),
        ),
    ]
