# Generated by Django 3.2 on 2022-09-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20220915_1841'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likecomment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='likecomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='likecomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='DislikeComment',
        ),
        migrations.DeleteModel(
            name='LikeComment',
        ),
    ]
