# Generated by Django 3.2 on 2022-09-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20220915_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedisliketweet',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.tweetstatus'),
        ),
    ]
